# Generated by Django 2.1.5 on 2019-03-17 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('adress', models.CharField(max_length=100, verbose_name='Ulica i numer')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Kod pocztowy i miejscowość')),
                ('nip', models.PositiveIntegerField(verbose_name='NIP')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nazwa banku')),
                ('account_nr', models.CharField(max_length=26, verbose_name='Numer konta')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='/2019', max_length=7, unique=True, verbose_name='Numer faktury')),
                ('invoice_date', models.CharField(default='Warszawa, 2019-03-17', max_length=20, verbose_name='Data i miejsce wystawienia')),
                ('invoice_sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data sprzedaży')),
                ('invoice_payment_date', models.DateField(default=invoice.models.one_month_hence, verbose_name='Termin płatności')),
                ('payment', models.CharField(choices=[('przelew', 'przelew'), ('gotówka', 'gotówka')], default='transfer', max_length=10, verbose_name='Płatność')),
                ('comments', models.TextField(max_length=250, verbose_name='Uwagi')),
                ('sign', models.CharField(max_length=250, verbose_name='Wystawca')),
                ('invoice_b_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Buyer', verbose_name='Nabywca')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250, verbose_name='Nazwa')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('price', models.FloatField(verbose_name='Cena jednostki')),
                ('unit', models.CharField(choices=[('h', 'h'), ('1h x os.', '1h x os.'), ('szt.', 'szt.')], max_length=100, verbose_name='Jednostka')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='Usługi')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('adress', models.CharField(max_length=100, verbose_name='Ulica i numer')),
                ('postal_code', models.CharField(max_length=100, verbose_name='Kod pocztowy i miejscowość')),
                ('nip', models.PositiveIntegerField(verbose_name='NIP')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nazwa banku')),
                ('account_nr', models.CharField(max_length=26, verbose_name='Numer konta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_s_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Seller', verbose_name='Sprzedawca'),
        ),
    ]
