# Generated by Django 2.1.5 on 2019-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='comments',
            field=models.TextField(default='Faktura za miesiąc March 2019.', max_length=250, verbose_name='Uwagi'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(default='Warszawa, 2019-03-27', max_length=20, verbose_name='Data i miejsce wystawienia'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_payment_date',
            field=models.DateField(default='2019-04-26', verbose_name='Termin płatności'),
        ),
    ]
