# Generated by Django 2.1.5 on 2019-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Nabywca', 'verbose_name_plural': 'Nabywcy'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Sprzedawca', 'verbose_name_plural': 'Sprzedawcy'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(default='Warszawa, 2019-03-25', max_length=20, verbose_name='Data i miejsce wystawienia'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='/2019', max_length=7, verbose_name='Numer faktury'),
        ),
    ]
