# Generated by Django 2.1.5 on 2019-03-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190325_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-invoice_sale_date',), 'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
    ]
