# Generated by Django 2.1.5 on 2019-03-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20190325_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-invoice_number',), 'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
    ]
